name: Sync Salmon Directory
description: Syncs a directory to a bucket using rclone.
author: "deephaven"
inputs:
  source:
    required: true
    type: string
    description: "The source directory to sync."
  destination:
    required: true
    type: string
    description: "The destination directory to sync. Relative to the bucket. It is recommended to use the GitHub repo path (such as deephaven/salmon-sync) as the minimum base to prevent collisions."
  bucket:
    required: true
    type: string
    description: "The bucket to sync to."
  aws-role:
    required: true
    type: string
    description: "The AWS role to assume."
  temporary:
    required: false
    type: boolean
    description: "If true, the files will be marked as temporary and deleted after 14 days."

runs:
  using: "composite"
  steps:
    - name: Setup rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        version: v1.68.1

    - name: AWS OIDC Auth
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2 # Docs are hosted in us-east-2
        role-to-assume: ${{ inputs.aws-role }}

    - name: Sync source to destination
      shell: bash
      env:
        RCLONE_S3_PROVIDER: AWS
        RCLONE_S3_REGION: us-east-2
        RCLONE_S3_ENV_AUTH: true
        RCLONE_S3_NO_CHECK_BUCKET: true # Don't try to create the bucket and fail if it doesn't exist
      run: |
        rclone sync --fast-list --checksum ${{ inputs.source }} :s3:${{ inputs.bucket }}/${{ inputs.destination }} ${{ inputs.temporary && '--header-upload "x-amz-tagging: temporary=true"' }}
